add grapql support
youngmonkeys/ezyhttp pull request #13
Opened 2021-09-03 10:42 UTC by tvd12

2021-09-05 13:46 UTC, vu-luong requested changes

2021-09-05 13:46 UTC, vu-luong commented on ezyhttp-server-graphql/src/main/java/com/tvd12/ezyhttp/server/graphql/controller/GraphQLController.java
> +	}
Chỗ này là @DoPost("/graphql") phải không anh? Mà em sửa lại vẫn không gửi được POST. Nó báo `method POST not allowed`

2021-09-07 02:00 UTC, vu-luong commented
Em thấy anh đang map query với DataFetcher thông qua operationName. Em đọc thì thấy thằng operationName này là optional, chỉ phải dùng khi query có nhiều operations, e.g.:
```
{
    "query": "query q1{greeting} query q2{artifactRepositories{id}}",
    "operationName": "q2"
}
```
Lý do là  "Only one operation will execute at a time". Có thể gửi lên nhiều query, nhưng chỉ trả về response tương ứng với thằng operationName.

Em thử query thông thường với spring thì chỉ cần gửi lên như sau là nó đã parse được rồi.
```
{
    "query": "{greeting}"
}
```

Em muốn code tiếp phần này để luyện tay java core, mình có nên merge luôn rồi em tạo PR mới, hay em code tiếp vào branch này anh nhỉ?

2021-09-27 13:15 UTC, tvd12 reviewed
LGTM

2021-09-27 13:15 UTC, merged